class_name Modification


enum Type {
	MOD_ARMOR,
	MOD_ARMOR_PERC,
	MOD_EXP_GRANTED,
	MOD_EXP_RECEIVED,
	MOD_SPELL_DAMAGE_RECEIVED,
	MOD_SPELL_DAMAGE_DEALT,
	MOD_SPELL_CRIT_DAMAGE,
	MOD_SPELL_CRIT_CHANCE,
	MOD_BOUNTY_GRANTED,
	MOD_BOUNTY_RECEIVED,
	MOD_ATK_CRIT_CHANCE,
	MOD_ATK_CRIT_DAMAGE,
	MOD_ATK_DAMAGE_RECEIVED,
	MOD_ATTACKSPEED,
	MOD_MULTICRIT_COUNT,
	MOD_ITEM_CHANCE_ON_KILL,
	MOD_ITEM_QUALITY_ON_KILL,
	MOD_ITEM_CHANCE_ON_DEATH,
	MOD_ITEM_QUALITY_ON_DEATH,
	MOD_BUFF_DURATION,
	MOD_DEBUFF_DURATION,
	MOD_TRIGGER_CHANCES,
	MOD_MOVESPEED,
	MOD_MOVESPEED_ABSOLUTE,
	MOD_DAMAGE_BASE,
	MOD_DAMAGE_BASE_PERC,
	MOD_DAMAGE_ADD,
	MOD_DAMAGE_ADD_PERC,
	MOD_DPS_ADD,
	MOD_HP,
	MOD_HP_PERC,
	MOD_HP_REGEN,
	MOD_HP_REGEN_PERC,
	MOD_MANA,
	MOD_MANA_PERC,
	MOD_MANA_REGEN,
	MOD_MANA_REGEN_PERC,

	MOD_DMG_TO_MASS,
	MOD_DMG_TO_NORMAL,
	MOD_DMG_TO_CHAMPION,
	MOD_DMG_TO_BOSS,
	MOD_DMG_TO_AIR,

	MOD_DMG_TO_UNDEAD,
	MOD_DMG_TO_MAGIC,
	MOD_DMG_TO_NATURE,
	MOD_DMG_TO_ORC,
	MOD_DMG_TO_HUMANOID,

	MOD_DMG_FROM_ASTRAL,
	MOD_DMG_FROM_DARKNESS,
	MOD_DMG_FROM_NATURE,
	MOD_DMG_FROM_FIRE,
	MOD_DMG_FROM_ICE,
	MOD_DMG_FROM_STORM,
	MOD_DMG_FROM_IRON,
}


var type: Modification.Type
var value_base: float
var level_add: float


func _init(type_arg: Modification.Type, value_base_arg: float, level_add_arg: float):
	type = type_arg
	value_base = value_base_arg
	level_add = level_add_arg


func get_tooltip_text() -> String:
	var type_string: String = "type string"
	var text: String = "+%d%% %s (+%d%%/lvl)\n" % [floor(value_base * 100), type_string, floor(level_add * 100)]

	return text
